Fixed "error[E0502]: cannot borrow `view` as mutable because it is also borrowed as immutable    --> packages\blitz-winrt\src\view_impl.rs:346:89     | 346 |             if let (Some(ref document), Some(ref mut renderer)) = (&view.document, &mut view.renderer) {     |                                                                   ----------------------^^^^----------     |                                                                   | |                   |     |                                                                   | |                   mutable borrow occurs here     |                                                                   | immutable borrow occurs here     |                                                                   immutable borrow later used here     |"